import type { MedicalSpecialty } from "./client";

/**
 * Marketing/clinical service lines per specialty. Clients multi-select from the union of their specialties.
 */
export const SPECIALTY_SERVICES: Record<MedicalSpecialty, readonly string[]> = {
  Gynaecology: [
    "Well-woman & preventive screening",
    "Pap smear & cervical screening",
    "HPV vaccination & counseling",
    "Menstrual disorders & fibroids",
    "PCOS & hormonal health",
    "Menopause & perimenopause",
    "Contraception & family planning",
    "Pelvic pain & endometriosis",
    "Minimally invasive gynecologic surgery",
    "Preconception & fertility work-up",
  ],
  "Fertility & IVF": [
    "IVF & embryo transfer",
    "IUI (intrauterine insemination)",
    "Fertility assessment (AMH, ultrasound)",
    "Egg & embryo freezing",
    "Male factor infertility",
    "Recurrent pregnancy loss clinic",
    "Ovulation induction",
    "Donor egg/sperm programs",
    "ERA & implantation testing",
    "Lifestyle & nutrition for fertility",
  ],
  Paediatrics: [
    "Newborn & well-baby visits",
    "Immunization schedules",
    "Growth & developmental screening",
    "Feeding, nutrition & weaning",
    "Fever & acute illness care",
    "Asthma & allergy management",
    "ADHD & developmental concerns",
    "Adolescent health",
    "Travel & school health forms",
    "Lactation & newborn feeding support",
  ],
  "Dermatology & Cosmetology": [
    "Acne & scar treatment",
    "Psoriasis & eczema care",
    "Skin cancer screening",
    "Mole mapping & biopsy",
    "Hair loss evaluation",
    "Laser & light therapies",
    "Chemical peels & medi-facials",
    "Injectable aesthetics",
    "Pediatric dermatology",
    "Patch testing & contact allergy",
  ],
  Orthopaedics: [
    "Joint pain & arthritis care",
    "Sports injury clinic",
    "Fracture & trauma care",
    "Knee & shoulder arthroscopy",
    "Joint replacement program",
    "Spine & back pain",
    "Physio-linked rehab",
    "Bone health & osteoporosis",
    "Pediatric orthopaedics",
    "Work-related MSK assessment",
  ],
  Cardiology: [
    "Hypertension & lipid clinic",
    "ECG & ambulatory monitoring",
    "Echocardiography",
    "Heart failure program",
    "Ischemic heart disease follow-up",
    "Preventive cardiology",
    "Cardiac rehab",
    "Palpitations & arrhythmia work-up",
    "Valvular heart disease",
    "Pre-op cardiac clearance",
  ],
  Dentistry: [
    "Routine dental check-ups",
    "Scaling & periodontal care",
    "Fillings & restorative work",
    "Root canal therapy",
    "Crowns & bridges",
    "Dental implants",
    "Orthodontics & aligners",
    "Pediatric dentistry",
    "Cosmetic whitening & veneers",
    "Emergency dental care",
  ],
  Physiotherapy: [
    "Post-surgical rehabilitation",
    "Sports physiotherapy",
    "Neck & back pain programs",
    "Stroke & neuro rehab",
    "Geriatric mobility training",
    "Dry needling & manual therapy",
    "Women's health physio",
    "Workstation ergonomics",
    "ACL & knee rehab protocols",
    "Home exercise planning",
  ],
  Neurology: [
    "Headache & migraine clinic",
    "Epilepsy care",
    "Stroke follow-up & prevention",
    "Parkinson's & movement disorders",
    "Peripheral neuropathy",
    "Memory & cognitive assessment",
    "EMG & nerve studies",
    "Multiple sclerosis care",
    "Sleep-related neurology",
    "Botulinum toxin for spasticity/migraine",
  ],
  "Psychiatry & Mental Health": [
    "Depression & anxiety care",
    "Medication management",
    "CBT & counseling referrals",
    "ADHD assessment (adult/child)",
    "Bipolar disorder follow-up",
    "Stress & burnout programs",
    "Sleep psychiatry",
    "Addiction psychiatry liaison",
    "Perinatal mental health",
    "Crisis safety planning",
  ],
  Oncology: [
    "Chemotherapy day care",
    "Immunotherapy & targeted therapy",
    "Tumor board coordination",
    "Palliative symptom control",
    "Cancer screening education",
    "Breast & GI oncology focus",
    "Survivorship clinics",
    "Nutrition during treatment",
    "Port care & line management",
    "Clinical trial information",
  ],
  Ophthalmology: [
    "Comprehensive eye exams",
    "Cataract evaluation & surgery",
    "Glaucoma screening & treatment",
    "Diabetic retinopathy screening",
    "Dry eye & allergy eye care",
    "Pediatric eye exams",
    "Refractive surgery counseling",
    "Uveitis & retina referrals",
    "Low vision aids",
    "Emergency eye care",
  ],
  ENT: [
    "Hearing tests & audiology",
    "Sinusitis & nasal obstruction",
    "Tonsil & adenoid care",
    "Voice & swallow disorders",
    "Vertigo & balance clinic",
    "Allergy-related ENT",
    "Sleep apnea surgery evaluation",
    "Pediatric ENT",
    "Thyroid neck mass work-up",
    "Epistaxis & emergency ENT",
  ],
  Gastroenterology: [
    "GERD & dyspepsia clinic",
    "IBS & functional GI care",
    "Inflammatory bowel disease",
    "Liver disease & hepatitis",
    "Colonoscopy screening",
    "Endoscopy services",
    "Celiac & malabsorption",
    "Pancreatobiliary disorders",
    "Nutrition & GI dietetics",
    "GI cancer surveillance",
  ],
  Nephrology: [
    "Chronic kidney disease care",
    "Dialysis education & planning",
    "Hypertension in CKD",
    "Electrolyte disorders",
    "Glomerular disease work-up",
    "Transplant follow-up liaison",
    "Acute kidney injury recovery",
    "Anemia of CKD management",
    "Stone prevention (metabolic)",
    "Diabetic kidney disease",
  ],
  "Endocrinology & Diabetes": [
    "Type 1 & type 2 diabetes care",
    "Insulin pump & CGM education",
    "Thyroid disorders",
    "PCOS endocrine management",
    "Osteoporosis & calcium disorders",
    "Adrenal disorders",
    "Pituitary disorders",
    "Obesity & metabolic clinic",
    "Gestational diabetes",
    "Hypoglycemia evaluation",
  ],
  Urology: [
    "Kidney stone prevention & treatment",
    "BPH & LUTS management",
    "Prostate cancer screening",
    "Male infertility evaluation",
    "UTI & recurrent infection clinic",
    "Incontinence & pelvic floor (male)",
    "Pediatric urology",
    "Hematuria work-up",
    "Andrology & erectile dysfunction",
    "Oncologic urology coordination",
  ],
  Pulmonology: [
    "Asthma & COPD clinic",
    "Pulmonary function testing",
    "Sleep apnea evaluation",
    "Interstitial lung disease",
    "Tuberculosis & infection screening",
    "Smoking cessation",
    "Long COVID breathlessness",
    "Home oxygen assessment",
    "Bronchoscopy referrals",
    "Occupational lung disease",
  ],
  Rheumatology: [
    "Rheumatoid arthritis care",
    "Lupus & connective tissue disease",
    "Ankylosing spondylitis & SpA",
    "Gout & crystal arthritis",
    "Osteoarthritis injections",
    "Osteoporosis & bone health",
    "Vasculitis coordination",
    "Fibromyalgia & chronic pain",
    "Pediatric rheumatology liaison",
    "Biologic therapy monitoring",
  ],
  "General Surgery": [
    "Hernia repair",
    "Gallbladder surgery",
    "Appendectomy",
    "Breast lump evaluation",
    "Thyroid surgery",
    "Hemorrhoids & proctology",
    "Soft tissue mass excision",
    "Trauma & acute surgical care",
    "Pre-op assessment",
    "Post-op wound care",
  ],
  "General Medicine": [
    "Preventive health check-ups",
    "Chronic disease panels",
    "Hypertension & diabetes primary care",
    "Travel medicine & vaccines",
    "Fatigue & weight management",
    "Respiratory infections",
    "Geriatric comprehensive care",
    "Pre-employment medicals",
    "Home visit coordination",
    "Care coordination & referrals",
  ],
  "Ayurveda & Wellness": [
    "Dosha-based consultation",
    "Panchakarma programs",
    "Stress & lifestyle balance",
    "Digestive wellness (Agni)",
    "Joint care (Abhyanga + therapy)",
    "Sleep & routine counseling",
    "Seasonal detox education",
    "Women's wellness (Ayurveda)",
    "Immunity & rasayana guidance",
    "Yoga-integrated wellness",
  ],
  Homeopathy: [
    "Constitutional homeopathy consult",
    "Allergy & atopic conditions",
    "Migraine & recurrent headaches",
    "Pediatric homeopathy",
    "Hormonal & menstrual support",
    "Anxiety & mild mood support",
    "Digestive functional disorders",
    "Skin conditions (eczema)",
    "Autoimmune support (adjunct)",
    "Travel & acute remedies",
  ],
  "Nutrition & Dietetics": [
    "Weight management programs",
    "Diabetes meal planning",
    "PCOS nutrition",
    "Renal diet counseling",
    "Post-bariatric nutrition",
    "Sports nutrition",
    "Prenatal & pediatric feeding",
    "Therapeutic elimination diets",
    "Tube feeding & hospital diet liaison",
    "Corporate wellness talks",
  ],
  Anesthesiology: [
    "Pre-operative anesthesia assessment",
    "Regional anesthesia & nerve blocks",
    "Labor epidural & obstetric anesthesia",
    "Day-care anesthesia protocols",
    "Chronic pain injections (selected)",
    "Post-operative nausea prevention",
    "Difficult airway planning",
    "Sedation for endoscopy & imaging",
    "Enhanced recovery after surgery liaison",
    "Pediatric anesthesia coordination",
  ],
  "Critical Care Medicine": [
    "ICU hemodynamic monitoring",
    "Mechanical ventilation & weaning",
    "Sepsis bundles & early goal-directed care",
    "Acute kidney injury in ICU",
    "Delirium prevention & sedation holds",
    "Multi-organ failure support",
    "Post-operative ICU pathway",
    "Family updates & goals-of-care liaison",
    "Nutrition & glycemic control in ICU",
    "Long ICU stay rehabilitation planning",
  ],
  "Emergency Medicine": [
    "24/7 emergency physician coverage",
    "Chest pain & STEMI pathway",
    "Stroke alert & neurology liaison",
    "Polytrauma stabilization",
    "Acute poisoning & overdose care",
    "Pediatric emergency protocols",
    "Minor procedures & wound management",
    "Fast-track observation unit",
    "Disaster & mass casualty readiness",
    "EMS coordination & transfer hub",
  ],
  "Geriatric Medicine": [
    "Comprehensive geriatric assessment",
    "Falls & fracture prevention",
    "Polypharmacy review & deprescribing",
    "Dementia & caregiver support",
    "Frailty screening & mobility plans",
    "Continence & nutrition in elders",
    "Home safety & geriatric syndromes",
    "Pre-operative optimization (elderly)",
    "Palliative symptom liaison",
    "Age-friendly transitions of care",
  ],
  "Infectious Diseases": [
    "HIV & viral hepatitis care",
    "Tuberculosis screening & treatment",
    "Travel vaccines & tropical fever work-up",
    "Hospital-acquired infection liaison",
    "Antibiotic stewardship consult",
    "Recurrent UTI & multidrug-resistant bugs",
    "Post-operative wound infection review",
    "Immunocompromised fever protocols",
    "Sexual health STI screening",
    "Outbreak & infection control liaison",
  ],
  Neonatology: [
    "NICU intensive care",
    "Prematurity & growth follow-up",
    "Respiratory distress & surfactant pathways",
    "Jaundice phototherapy protocols",
    "Breastfeeding & lactation liaison",
    "Congenital anomaly screening coordination",
    "Developmental follow-up clinic",
    "Parent counseling & kangaroo care",
    "Safe sleep & home oxygen transition",
    "High-risk newborn neuro follow-up",
  ],
  "Pain Medicine": [
    "Multimodal chronic pain plans",
    "Neuropathic pain management",
    "Headache & migraine procedures liaison",
    "Back & spine injection programs",
    "Cancer pain palliative liaison",
    "Fibromyalgia & centralized pain care",
    "Medication taper & opioid stewardship",
    "Interventional pain referrals coordination",
    "Physio-linked rehab plans",
    "Functional restoration programs",
  ],
  "Plastic & Reconstructive Surgery": [
    "Cosmetic breast & body contouring",
    "Rhinoplasty & facial aesthetics",
    "Scar revision & skin lesion excision",
    "Cleft & craniofacial liaison",
    "Burn & wound reconstruction",
    "Hand trauma & microsurgery referrals",
    "Post-mastectomy reconstruction",
    "Non-surgical aesthetics coordinator",
    "Gender-affirming surgical liaison",
    "Laser & scar resurfacing programs",
  ],
  "Radiology & Imaging": [
    "MRI & CT scheduling coordination",
    "Ultrasound & Doppler imaging",
    "Mammography & breast imaging pathway",
    "Interventional radiology referrals",
    "PET-CT oncology staging liaison",
    "Pediatric sedation imaging",
    "Contrast allergy & renal-safe protocols",
    "Same-day emergency imaging triage",
    "Radiation dose optimization messaging",
    "Report turnaround & subspecialty reads",
  ],
  "Sports Medicine": [
    "ACL & ligament injury clinic",
    "Concussion return-to-play protocols",
    "Running gait & overuse injury screening",
    "Injection therapies for athletes",
    "Shoulder & elbow throwing programs",
    "Cartilage & meniscus preservation liaison",
    "Sports nutrition & hydration plans",
    "Pre-participation physicals",
    "Pitch counts & youth injury prevention",
    "Performance recovery & load management",
  ],
  "Vascular Surgery": [
    "Varicose veins & venous insufficiency",
    "Deep vein thrombosis prevention",
    "Peripheral artery disease & claudication",
    "Carotid disease screening liaison",
    "Aortic aneurysm surveillance",
    "Dialysis access creation & salvage",
    "Diabetic foot & limb preservation",
    "Endovascular vs open surgery counseling",
    "Post-operative graft surveillance",
    "Wound care & hyperbaric liaison",
  ],
};

/** Union of service labels for the given specialties (deduped, stable sort). */
export function getAvailableServicesForSpecialties(specialties: string[]): string[] {
  const set = new Set<string>();
  for (const sp of specialties) {
    const list = SPECIALTY_SERVICES[sp as MedicalSpecialty];
    if (list) {
      for (const s of list) set.add(s);
    }
  }
  return [...set].sort((a, b) => a.localeCompare(b));
}

/** Max length for a custom (free-text) service line. */
export const MAX_CUSTOM_SERVICE_LENGTH = 120;

/** Max number of service lines per client (catalog + custom). */
export const MAX_SERVICES_PER_CLIENT = 40;

/** True if string is acceptable as an additional custom service (not necessarily in catalog). */
export function isValidCustomServiceName(raw: string): boolean {
  const t = raw.trim();
  if (t.length < 2 || t.length > MAX_CUSTOM_SERVICE_LENGTH) return false;
  if (/[\r\n\t<>{}`\\]/.test(t)) return false;
  return true;
}

/** Each entry is either from the specialty catalog or a validated custom label. */
export function validateClientServices(services: string[], specialties: string[]): boolean {
  if (specialties.length === 0) return services.length === 0;
  if (services.length > MAX_SERVICES_PER_CLIENT) return false;
  const catalog = new Set(getAvailableServicesForSpecialties(specialties));
  return services.every((s) => catalog.has(s) || isValidCustomServiceName(s));
}

/** @deprecated use validateClientServices — kept for older imports */
export function servicesAllowedForSpecialties(services: string[], specialties: string[]): boolean {
  return validateClientServices(services, specialties);
}
