import ExcelJS from "exceljs";
import type { CalendarPost } from "@hc/shared";
import { MEDICAL_SPECIALTIES } from "@hc/shared";

const HEADER_BG = "FF1E3A5F";
/** Light blue — AI-generated row indicator */
const AI_ROW_FILL = "FFDCE6F1";
const COL_WIDTHS = [16, 10, 20, 12, 20, 45, 80];

const PALETTE = [
  "FF4472C4",
  "FF70AD47",
  "FFFFC000",
  "FFED7D31",
  "FF5B9BD5",
  "FF9F4F96",
  "FFFF6961",
  "FF264478",
  "FF00B0F0",
  "FFA5A5A5",
  "FF548235",
  "FFC65911",
  "FF7030A0",
  "FF92D050",
  "FF0070C0",
  "FFFF0000",
  "FF002060",
  "FF833C0C",
  "FF9966FF",
  "FFE7E6E6",
];

function buildSpecialtyDepartmentColorMap(): Record<string, string> {
  const map: Record<string, string> = {};
  MEDICAL_SPECIALTIES.forEach((sp, i) => {
    map[sp] = PALETTE[i % PALETTE.length];
  });
  map["Awareness / Festival"] = "FFFFF3CD";
  map["Awareness"] = "FFFFF3CD";
  return map;
}

function departmentCellArgb(
  department: string,
  code: CalendarPost["code"],
  specialtyColorMap: Record<string, string>
): string {
  if (code === "AWR") {
    return specialtyColorMap["Awareness / Festival"] ?? "FFFFF3CD";
  }
  const direct = specialtyColorMap[department.trim()];
  if (direct) return direct;
  const depLower = department.toLowerCase();
  for (const sp of MEDICAL_SPECIALTIES) {
    if (depLower.includes(sp.toLowerCase()) || sp.toLowerCase().includes(depLower)) {
      return specialtyColorMap[sp] ?? "FFE7E6E6";
    }
  }
  return "FFE7E6E6";
}

/**
 * Builds the workbook in memory (buffer) for reliable uploads and containerized environments.
 */
export async function buildExcel(jobId: string, rows: CalendarPost[]): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  const specialtyColorMap = buildSpecialtyDepartmentColorMap();

  const sheet = workbook.addWorksheet("Calendar", {
    views: [{ state: "frozen", ySplit: 1 }],
  });

  const headers = [
    "Date",
    "Code",
    "Department",
    "Type",
    "Style",
    "Text in Image",
    "Supporting Text",
    "AI Generated",
  ];

  const headerRow = sheet.addRow(headers);
  headerRow.height = 28;
  headerRow.eachCell((cell) => {
    cell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: HEADER_BG },
    };
    cell.font = { bold: true, size: 12, color: { argb: "FFFFFFFF" } };
    cell.alignment = { vertical: "top", wrapText: true };
  });

  for (const post of rows) {
    const codeDisplay = post.isAIAdded ? `➕ ADDED — ${post.code}` : post.code;

    const dataRow = sheet.addRow([
      post.date,
      codeDisplay,
      post.department,
      post.type,
      post.style,
      post.textInImage,
      post.supportingText,
      "Yes",
    ]);

    const deptArgb = departmentCellArgb(post.department, post.code, specialtyColorMap);

    dataRow.eachCell((cell, colNumber) => {
      const isDeptCol = colNumber === 3;
      cell.fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: isDeptCol ? deptArgb : AI_ROW_FILL },
      };
      cell.font = { size: 11 };
      if (colNumber === 7) {
        cell.font = { size: 10, color: { argb: "FF444444" } };
      }
      cell.alignment = { vertical: "top", wrapText: true };
    });
  }

  COL_WIDTHS.forEach((w, i) => {
    sheet.getColumn(i + 1).width = w;
  });
  sheet.getColumn(8).width = 14;

  const legend = workbook.addWorksheet("Legend");
  legend.addRow(["Healthcare Content Calendar — AI-assisted rows"]);
  legend.addRow([
    "Rows in 'Calendar' are generated by Claude; 'AI Generated' column is Yes for model output.",
  ]);
  legend.addRow(["Department colors map to clinical specialty themes (see Department column)."]);
  legend.addRow([`Export job id: ${jobId}`]);
  legend.getColumn(1).width = 90;

  const buf = await workbook.xlsx.writeBuffer();
  return Buffer.from(buf);
}
